# kind: PersistentVolume
# apiVersion: v1
# metadata:
#   name: mysql-initdb-pv-volume
#   labels:
#     type: local
#     app: mysql
# spec:
#   storageClassName: manual
#   capacity:
#     storage: 1Mi
#   accessModes:
#     - ReadOnlyMany
#   hostPath:
#     path: "C:/Users/Hp/Desktop/spring-boot-vue/kube/scripts"
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: mysql-initdb-pv-claim
#   labels:
#     app: mysql
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadOnlyMany
#   resources:
#     requests:
#       storage: 1Mi
# ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
      nodePort: 30000
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:13.1-alpine
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secrets
                  key: PASSWORD
            - name: POSTGRES_DB
              value: test
          imagePullPolicy: Always
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
          # # volumeMounts:
          #   - mountPath: /docker-entrypoint-initdb.d
          #     name: mysql-initdb
      volumes:
      #   - name: mysql-initdb
      #     persistentVolumeClaim:
      #       claimName: mysql-initdb-pv-claim
      # # volumes:
        - name: pgdata
          persistentVolumeClaim:
            claimName: postgres-pvc