version: '2'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: ./backend
    container_name: app
    ports:
        - "9000:9000"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/test
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    #   - SPRING_JPA_HIBERNATE_DDL_AUTO=update
          
  db:
    image: 'postgres:latest'
    build:
      context: ./db
    container_name: db
    volumes:
        - postgres_data:/var/lib/postgresql/data/
        # - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
volumes:
    postgres_data: